[db_server]
Server1 ansible_host=192.168.56.119 ansible_user=benedicto target_user=benedicto ansible_pyhton_interpreter=/usr/bin/python3.13
[web_server]
Server2 ansible_host=192.168.56.120 ansible_user=benedicto target_user=benedicto ansible_pyhton_interpreter=/usr/bin/python3.13
[file_server]
Server3 ansible_host=192.168.56.121 ansible_user=benedicto target_user=benedicto ansible_pyhton_interpreter=/usr/bin/python3.13
[RedHat]
CentOS ansible_host=10.0.2.15 ansible_user=benedicto target_user=benedicto
